/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { UserShoppingList } from "./UserShoppingList";
import { UserShoppingListCountArgs } from "./UserShoppingListCountArgs";
import { UserShoppingListFindManyArgs } from "./UserShoppingListFindManyArgs";
import { UserShoppingListFindUniqueArgs } from "./UserShoppingListFindUniqueArgs";
import { DeleteUserShoppingListArgs } from "./DeleteUserShoppingListArgs";
import { UserShoppingListService } from "../userShoppingList.service";
@graphql.Resolver(() => UserShoppingList)
export class UserShoppingListResolverBase {
  constructor(protected readonly service: UserShoppingListService) {}

  async _userShoppingListsMeta(
    @graphql.Args() args: UserShoppingListCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [UserShoppingList])
  async userShoppingLists(
    @graphql.Args() args: UserShoppingListFindManyArgs
  ): Promise<UserShoppingList[]> {
    return this.service.userShoppingLists(args);
  }

  @graphql.Query(() => UserShoppingList, { nullable: true })
  async userShoppingList(
    @graphql.Args() args: UserShoppingListFindUniqueArgs
  ): Promise<UserShoppingList | null> {
    const result = await this.service.userShoppingList(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserShoppingList)
  async deleteUserShoppingList(
    @graphql.Args() args: DeleteUserShoppingListArgs
  ): Promise<UserShoppingList | null> {
    try {
      return await this.service.deleteUserShoppingList(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
