/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  ShoppingListProduct as PrismaShoppingListProduct,
} from "@prisma/client";

export class ShoppingListProductServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ShoppingListProductCountArgs, "select">
  ): Promise<number> {
    return this.prisma.shoppingListProduct.count(args);
  }

  async shoppingListProducts<T extends Prisma.ShoppingListProductFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ShoppingListProductFindManyArgs>
  ): Promise<PrismaShoppingListProduct[]> {
    return this.prisma.shoppingListProduct.findMany<Prisma.ShoppingListProductFindManyArgs>(
      args
    );
  }
  async shoppingListProduct<T extends Prisma.ShoppingListProductFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ShoppingListProductFindUniqueArgs>
  ): Promise<PrismaShoppingListProduct | null> {
    return this.prisma.shoppingListProduct.findUnique(args);
  }
  async createShoppingListProduct<
    T extends Prisma.ShoppingListProductCreateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.ShoppingListProductCreateArgs>
  ): Promise<PrismaShoppingListProduct> {
    return this.prisma.shoppingListProduct.create<T>(args);
  }
  async updateShoppingListProduct<
    T extends Prisma.ShoppingListProductUpdateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.ShoppingListProductUpdateArgs>
  ): Promise<PrismaShoppingListProduct> {
    return this.prisma.shoppingListProduct.update<T>(args);
  }
  async deleteShoppingListProduct<
    T extends Prisma.ShoppingListProductDeleteArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.ShoppingListProductDeleteArgs>
  ): Promise<PrismaShoppingListProduct> {
    return this.prisma.shoppingListProduct.delete(args);
  }
}
